export enum AttributeOperatorType {
  EQUALS = 'EQUALS',
  NOTEQUALS = 'NOTEQUALS',
  CONTAINS = 'CONTAINS',
  NOTCONTAINS = 'NOTCONTAINS',
  STARTSWITH = 'STARTSWITH',
  ENDSWITH = 'ENDSWITH',
  REGEX = 'REGEX',
}
