export enum BanType {
  STAKE_ADDRESS_BAN = 'STAKE_ADDRESS_BAN',
  ASSET_FINGERPRINT_BAN = 'ASSET_FINGERPRINT_BAN',
  DISCORD_ID_BAN = 'DISCORD_ID_BAN',
  EXACT_NAME_BAN = 'EXACT_NAME_BAN',
  PARTIAL_NAME_BAN = 'PARTIAL_NAME_BAN',
  FUZZY_NAME_BAN = 'FUZZY_NAME_BAN',
}
