export enum MarketplaceLinkType {
  MARKETPLACE = 'MARKETPLACE',
  PIXLPAGE = 'PIXLPAGE',
  CNFTJUNGLE = 'CNFTJUNGLE',
  POOLPMHANDLE = 'POOLPMHANDLE',
  POOLPM = 'POOLPM',
  TAPTOOLS = 'TAPTOOLS',
}
